'use client';
import Image from 'next/image';
import Logo from '@/components/Logo';
import CTA from '@/components/CTA';
import Gallery from '@/components/Gallery';
import FAQ from '@/components/FAQ';
import { useLanguage } from '@/components/LanguageProvider';
import { product, money } from '@/lib/product';

export default function Home() {
  const { t } = useLanguage();
  const benefits = [t('benefitDance'), t('benefitVoice'), t('benefitEmoji'), t('benefitJoints'), t('benefitControl'), t('benefitCompanion')];
  const testimonials = [[t('testimonial1'), 'Sushma Karki', 'Kathmandu', '★★★★★'], [t('testimonial2'), 'Ramesh Thapa', 'Pokhara', '★★★★★'], [t('testimonial3'), 'Anisha Shrestha', 'Lalitpur', '★★★★☆']];
  return <main>
    <div className="bg-[#38BDF8] py-2 text-center text-xs font-bold tracking-wide text-ink">{t('deliveryBar')}</div>
    <header className="container flex items-center justify-between py-5"><Logo/><a href="#showcase" className="hidden text-sm font-bold text-ink/60 md:block">{t('explore')}</a><CTA label={t('buyNow')}/></header>
    <section className="grid-bg overflow-hidden"><div className="container grid items-center gap-10 py-12 md:grid-cols-[1.05fr_.95fr] md:py-20"><div><p className="mb-5 text-sm font-black uppercase tracking-[.2em] text-electric">{t('playtime')}</p><h1 className="max-w-xl text-5xl font-black leading-[.98] tracking-[-.05em] md:text-7xl">{t('heroTitle')}</h1><p className="mt-6 max-w-lg text-lg leading-8 text-ink/65">{t('heroDescription')}</p><div className="mt-8 flex flex-wrap gap-3"><CTA label={t('purchaseNow')}/><CTA label={t('features')} secondary/></div><div className="mt-8 grid gap-3 text-sm font-black text-red-600 sm:grid-cols-3"><span><b className="mr-1 text-green-500">✓</b> {t('cod')}</span><span><b className="mr-1 text-green-500">✓</b> {t('kathmanduDelivery')}</span><span><b className="mr-1 text-green-500">✓</b> {t('easyOrdering')}</span></div></div><div className="relative mx-auto aspect-square w-full max-w-[500px] overflow-hidden rounded-[2.5rem] bg-sky shadow-glow"><Image src={product.images[0]} alt={product.name} fill className="object-cover" priority/><div className="absolute bottom-5 left-5 rounded-2xl bg-white/90 px-4 py-3 text-xs font-bold shadow-lg">{t('flexible')}<br/><span className="text-electric">{t('powerful')}</span></div></div></div></section>
    <section id="showcase" className="container grid gap-12 py-20 md:grid-cols-2 md:items-center"><Gallery images={product.images}/><div><p className="text-sm font-black uppercase tracking-[.2em] text-electric">{t('smart')}</p><h2 className="mt-3 text-4xl font-black tracking-tight md:text-5xl">{t('showcaseTitle')}</h2><p className="mt-5 leading-8 text-ink/65">{t('showcaseDescription')}</p><div className="mt-7 grid gap-3 sm:grid-cols-2">{benefits.map(b=><div key={b} className="rounded-2xl border border-ink/10 bg-white p-4 text-sm font-bold"><span className="mr-2 text-aqua">✦</span>{b}</div>)}</div><div className="mt-8 flex items-end gap-4"><div><span className="text-sm text-ink/40 line-through">{money(product.price)}</span><div className="text-4xl font-black text-electric">{money(product.offerPrice)}</div></div><span className="rounded-full bg-red-500 px-3 py-2 text-xs font-black text-white shadow-lg shadow-red-500/20">{t('save')}</span></div><p className="mt-2 text-sm font-bold text-ink/60">{t('delivery')}</p><div className="mt-7 flex flex-wrap gap-3"><CTA label={t('orderNow')}/><CTA label={t('buyNow')} secondary/></div></div></section>
    <section className="bg-[#7DD3FC] py-20"><div className="container"><div className="max-w-2xl"><p className="text-sm font-black uppercase tracking-[.2em] text-electric">{t('curious')}</p><h2 className="mt-3 text-4xl font-black tracking-tight md:text-5xl">{t('friend')}</h2></div><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{benefits.map((b,i)=><div key={b} className="rounded-3xl border border-white/70 bg-white/75 p-6 shadow-sm"><div className="mb-6 text-3xl text-electric">{['◉','♫','☻','✧','⌁','♡'][i]}</div><p className="font-bold leading-7">{b}</p></div>)}</div><div className="mt-10"><CTA label={t('smile')}/></div></div></section>
    <section className="container py-20"><div className="text-center"><p className="text-sm font-black uppercase tracking-[.2em] text-electric">{t('loved')}</p><h2 className="mt-3 text-4xl font-black tracking-tight">{t('reactions')}</h2></div><div className="mt-10 grid gap-5 md:grid-cols-3">{testimonials.map(([quote,name,place,stars])=><article key={name} className="rounded-3xl bg-white p-7 shadow-sm ring-1 ring-ink/5"><div className="text-sun">{stars}</div><p className="mt-5 text-sm leading-7 text-ink/70">{quote}</p><div className="mt-6 text-sm font-black">{name}</div><div className="text-xs text-ink/45">{place}</div></article>)}</div></section>
    <section className="bg-sky py-20"><div className="container"><div className="mb-10 text-center"><p className="text-sm font-black uppercase tracking-[.2em] text-electric">{t('questions')}</p><h2 className="mt-3 text-4xl font-black tracking-tight">{t('faqTitle')}</h2></div><FAQ faqs={t('faqs')}/></div></section>
    <section className="container py-20"><div className="relative overflow-hidden rounded-[2.5rem] bg-[#38BDF8] px-7 py-14 text-center text-ink md:px-10"><div className="absolute -right-20 -top-20 h-64 w-64 rounded-full bg-white/20"/><h2 className="relative text-4xl font-black tracking-tight md:text-5xl">{t('ready')}</h2><p className="relative mx-auto mt-4 max-w-xl text-ink/75">{t('ctaDescription')}</p><div className="relative mt-8"><CTA label={t('purchaseNow')}/></div></div></section>
    <footer className="border-t border-ink/10 py-8"><div className="container flex flex-col items-center justify-between gap-3 text-center text-xs text-ink/50 md:flex-row"><Logo/><span>kids Toy | Interactive play, delivered with care | 974733326</span></div></footer>
  </main>;
}
